#将静态内容部署到GitHub页面的简单工作流程
名称：将静态内容部署到页面

在……之上：
#在以默认分支为目标的推送上运行
推：
分支机构：["主要"]["主要"]

#允许您从“操作”选项卡手动运行此工作流
工作流程分派(_D)：

#设置GitHub_TOKEN的权限以允许部署到GitHub页面
权限：
内容：已读
页面：写入
id-token：写入

#只允许一个并发部署，跳过正在运行和最新排队之间排队的运行。
#但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发：
组：“”页“”
正在取消：假的

作业：
#单部署作业，因为我们刚刚部署
部署：
环境：
名称：github-pages
URL：${{steps.deployment.outputs.page_url}}{{steps.deployment.outputs.page_url}}
run-on:ubuntu-latest
步骤：
-名称：结帐
用途：操作/签出@v4
-名称：设置页面
用法：操作/configure-pages@v5
-名称：上传工件
用法：操作/上载-页面-工件@v3
和……一起：
#上传整个资源库
路径：“.”
-名称：部署到GitHub页面
身份标识：部署
uses: 用法：操作/部署页面@v4
